### ISSUE TITLE
[BUG] [MD] Replying to List Message

### ISSUE THREAD

**Issue by FoxyCodeX** [adiwajshing/Baileys#1120]
![IMG_20220106_201247](https://user-images.githubusercontent.com/94102324/148388255-e1421f62-ea7a-4516-a687-aa4257ea1934.jpg)

Does anyone know? Why does the Description follow when replying to a List Message?

**Comment by Fredwuz** [comment]
That's because Whatsapp will print out the full Title and the full Description when answering a list message. If the Description has more than 2 lines three dots will appear but in the reply will be the full description.
![image](https://user-images.githubusercontent.com/36505101/148843944-ffccfd17-2652-4cda-8b3a-5f9ff00fbf98.png)
![image](https://user-images.githubusercontent.com/36505101/148844246-9e790e40-94b1-44c8-8ffe-ad5e303fcc54.png)

**Comment by Jorsis** [comment]
i do it with this:

 var menesaje =  m.message.conversation ; // get what type of message it is -- text, image, video
 
   if (messageType === "conversation" || messageType === "messageContextInfo" || messageType === "extendedTextMessage"|| messageType === "templateButtonReplyMessage" ) {
                
                
                if (messageType === "messageContextInfo" && m.message.hasOwnProperty('buttonsResponseMessage')) { menesaje = m.message.buttonsResponseMessage.selectedDisplayText }
                if (messageType === "messageContextInfo" && m.message.hasOwnProperty('listResponseMessage')) { menesaje = m.message.listResponseMessage.title;  }
                if (messageType === "messageContextInfo" && m.message.hasOwnProperty('extendedTextMessage')) { menesaje = m.message.extendedTextMessage.text; }
                if (messageType === "templateButtonReplyMessage" ) { menesaje = m.message.templateButtonReplyMessage.selectedDisplayText; }
                
                
}
