### ISSUE TITLE
[BUG] "Unexpected status in 'admin': Bad Request(400)"

### ISSUE THREAD

**Issue by pedroayres** [adiwajshing/Baileys#1186]
**Describe the bug**

**To Reproduce**

1. Created a new connection
2. Closed the process & try start the project again

![](https://cdn.discordapp.com/attachments/725842574098694194/935523276539711528/Screen_Shot_2022-01-25_at_10.15.18.png)

![](https://cdn.discordapp.com/attachments/725842574098694194/935523276803964998/Screen_Shot_2022-01-25_at_10.14.58.png)

**Comment by sovsemsk** [comment]
have same issue

**Comment by VEXG** [comment]
u can do "@adiwajshing/baileys-md": "github:adiwajshing/baileys#multi-device", instead of this
![image](https://user-images.githubusercontent.com/83714022/151555695-bc99719d-bb82-4dd4-9827-beb146edbc5a.png)

and make sure its "makeWaSocket"
![image](https://user-images.githubusercontent.com/83714022/151555895-c520824c-a95e-48fc-a1ca-5f8ec5cf6434.png)
