### ISSUE TITLE
Missing the Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [adiwajshing/Baileys#1299]
The project is currently missing the Code of Conduct which defines standards for how to engage in a community. If you want to add that, then I would submit a PR along with the file.

**Comment by jackcokk** [comment]
I vote against that. Never has there been a vile fight in the issue section, commits or on the server.

We are a very small community that is 110% civil and I think we do not need that kind of virtue signalling here. 


It will be Adi's decision eventually but to me it seems like projecting a problem that doesn't even exist here to begin with since, again, everyone here gets along with each other.

My two cents.
