### ISSUE TITLE
[MD] Reconnect example when "Connection is Closed"

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1412]
Anyone can helpme with example to reconnect when the connection is closed without i need stop and start the process?

**Comment by rafosolima** [comment]
I have the same problem, when it does the reconnect it gives a timeout error and stops my application.

**Comment by itacirgabral** [comment]
I'm isolating every socket in one nodejs process, so you could kill it. But manager process is not easier.

The main process take care of every baileys children with my lovely patchpanel
- https://github.com/itacirgabral/motteteams/blob/main/motte/src/patchpanel.ts
Every successful connection will take a fork using envs to switch.
- https://github.com/itacirgabral/motteteams/blob/main/motte/src/zygote.ts#L224-L235

**Comment by rafosolima** [comment]
@itacirgabral @drauber 

I had an application that I participated in that used this same process of isolating the lib in separate node processes, but we had a lot of problems performing this process:

1- The application kept running even though it had problems that made it stop. (It doesn't kill the process, it just keeps it running without working you have to manually restart)

2- The monitoring ended up being problematic, because it wasn't clear who the instances corresponded to. (Even though there was a name for each instance to define them, it's horrible to try to map them in pm2)

3- Reconnection problems, because any update of the project it is necessary to restart the applications that does not guarantee in itself the reconnection with the qrcode.

With the in-memory management, by the application itself we can keep these problems, but when the lib breaks, the whole application stops, needing to restart it, for this reason we wanted to know what we could do to solve this timeout problem.

Translated with www.DeepL.com/Translator (free version)

====================================================================

Teve uma aplicação que participei que utilizava essa mesmo processo de isolar a lib em processos nodes separados, porém tivemos muitos problemas em realizar esse processo:

1- A aplicação se mantinha rodando mesmo tendo problemas que o fizeram parar. (Ele não mata o processo, so o mantêm rodando sem funcionar tem que reniciar manualmente)

2- O monitoramente acabou sendo problematico, porque não era claro as instancias de quem correspondiam. (Mesmo que para cada instancia estivesse um name para definilas é horrivel tentar mapealas no pm2)

3- Problemas de reconexão, porque qualquer atualização do projeto é necessário reiniciar as aplicações que não garante em si a renonexão com o qrcode.

Com o gerenciamento em memória, pela propria aplicação conseguimos manter esses problemas, porém quando a lib quebra, toda a aplicação para, necessitando reinicia-la, por esse motivo queriamos saber o que poderiamos fazer para solucionar esse problema de timeout.

**Comment by DwiRizqiH** [comment]
try using pm2, when it dies the app will automatically restart

sorry my english is too bad :/
