### ISSUE TITLE
How can i achieve mulltiple sessions. 

### ISSUE THREAD

**Issue by kaniket7209** [adiwajshing/Baileys#1447]
I would like to save the session to database for multiple sessions so that I can re use it.. For particular instance.. Can anyone help me out writing that function to store the current Instancr session to database?

**Comment by salman0ansari** [comment]
create a class, add functions for creating a session , deleting a session etc and give a unique id to every session you create so you can restore them easily

**Comment by kaniket7209** [comment]
Can you help me out as I m getting confused because the auth_session is managed using useSingleFileAuthState  ..
With that function

**Comment by kaniket7209** [comment]
And 1 more issue which I am facing is that after a scan or deletion of a session app needs a restart to reflect and re scan .. So How Can I acheive restart of express server

**Comment by HanzCEO** [comment]
@kaniket7209, i'm working in simplifying Baileys library. You can check my project `fabuya` [here](https://github.com/HanzHaxors/fabuya).

With fabuya, you can create clients easily and manage them in a simple array. Then, instead of using `useSingleFileAuthState` you can use fabuya's `AuthSave` class which simplify this. Check the example for AuthSave at [this link](https://github.com/HanzHaxors/fabuya/blob/3e20f16e6d70a0e67547d4d91918eb9a543d4910/Examples/authSaveDemo.js)

**Comment by salman0ansari** [comment]
> And 1 more issue which I am facing is that after a scan or deletion of a session app needs a restart to reflect and re scan .. So How Can I acheive restart of express server

are trying to create rest API ?
