### ISSUE TITLE
Baileys depends on vulnerable versions of "protobufjs" and "libsignal"

### ISSUE THREAD

**Issue by LinkTree3** [adiwajshing/Baileys#1896]
When doing an NPM install using `npm i @adiwajshing/baileys@latest`
NPM complains that Baileys depends on vulnerable versions of "protobufjs" which depends on a vulnerable version of libsignal
the only fix NPM offers is to downgrade to version 3.5.3

```
# npm audit report

protobufjs  <6.10.3
Severity: high
Prototype Pollution in protobufjs - https://github.com/advisories/GHSA-g954-5hwp-pp24
fix available via `npm audit fix --force`
Will install @adiwajshing/baileys@3.5.3, which is a breaking change
node_modules/libsignal/node_modules/protobufjs
  libsignal  *
  Depends on vulnerable versions of protobufjs
  node_modules/libsignal
    @adiwajshing/baileys  >=4.0.0
    Depends on vulnerable versions of libsignal
    node_modules/@adiwajshing/baileys

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by burstfreeze** [comment]
I'm fairly confident it's impossible for another client to inject a nonstandard object since the WA server would have to completely ignore the actual payload you are sending. So unless you think WA would deliberately send malformed data, I don't think that's a big problem. Even then I'm not sure if there was even something someone could do to your machine.

It's nice that you bring it up, I just wanted to make you aware that the issue **probably** is not as critical as it sounds

**Comment by LinkTree3** [comment]
> I'm fairly confident it's impossible for another client to inject a nonstandard object since the WA server would have to completely ignore the actual payload you are sending. So unless you think WA would deliberately send malformed data, I don't think that's a big problem. Even then I'm not sure if there was even something someone could do to your machine.
> 
> It's nice that you bring it up, I just wanted to make you aware that the issue **probably** is not as critical as the warning makes it sound

Yea I did figure it is probably a non issue, especially for my use case. but it's good to have this fixed just so NPM doesn't scream at you every time you install or update packages. Letting 1 package with a vulnerability in and ignoring it might cause you to miss other vulnerabilities that pop up in the future.
