### ISSUE TITLE
[BUG] fetch message does not return any result

### ISSUE THREAD

**Issue by satriowicaksn** [adiwajshing/Baileys#2231]
**Describe the bug**
after running for some time, fetch message doesn't give any result and after checking in json file the result is empty like this :

![image](https://user-images.githubusercontent.com/90515555/194547047-1f7ecf5a-da75-415e-b6f8-2981f4fbb26a.png)

 Is there a function that can be called to re-fetch all messages like when you just connected to WhatsApp?

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Fetch messages using store?.messages
4. Not return any result, maybe because json file is empty ??

**Expected behavior**
can call a function to refetch all messages if there is a problem as above

**Comment by satriowicaksn** [comment]
up

**Comment by Verzach3** [comment]
Are you saving the messages with the writeToFile function of the store?

**Comment by satriowicaksn** [comment]
yes @Verzach3 , I'm save the messages with writeToFile function on the store. can you help me ?

**Comment by Verzach3** [comment]
Show me the code, maybe i can find the issue

**Comment by jurajmatus** [comment]
1. There isn't any such function. I have gone through past issues also looking for this, but it was explained that's not even possible because of WhatsApp multidevice architecture [#1634]
2. The cause seems to be `writeToFile` like someone mentioned. You need to call after each change (ideally with some debounce), otherwise sudden crash of an application or its manual stop may cause the newest data never to be written
3. It's also possible that you haven't waited long enough. You must wait for `contacts.set`, `chats.set` and `messages.set` events (those bring in history) and only then you can interact with the client. From what I observed, usually 2 events of each will come (probably a recent history and then a longer history)
