### ISSUE TITLE
is it possible to send template with image?

### ISSUE THREAD

**Issue by ahmedRSA** [adiwajshing/Baileys#2265]
is it possible to send template with image?

**like 1 quickReply Button and 1 URL button 
with Image** 

### if yes please tell how.

thanks

**Comment by ahmedRSA** [comment]
bump

**Comment by BlackAmda** [comment]
```JS
const templateButtons = [
    {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
    {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
    {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const templateMessage = {
    caption: "Hi it's a template message",
    footer: "Baileys",
    templateButtons: templateButtons,
    image: {url: 'https://example.com/image.jpeg'}
}

const sendMsg = await sock.sendMessage(id, templateMessage);
```

**Comment by aidulcandra** [comment]
@BlackAmda I tried this but no luck

**Comment by BlackAmda** [comment]
> @BlackAmda I tried this but no luck

Please show me your code. Because this works perfectly for me.

Code:
![code](https://user-images.githubusercontent.com/83172207/197323164-e7f40b9a-bacd-49b9-b1b6-bce389d5373e.png)

Result:
![Screenshot](https://user-images.githubusercontent.com/83172207/197323193-af674f24-3b15-4a1e-b5a5-a245a691287c.jpeg)

**Comment by MaznAbdullah** [comment]
it work in whatsapp web only !
