### ISSUE TITLE
[BUG] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by M0in4** [adiwajshing/Baileys#2380]
SyntaxError: Cannot use import statement outside a module

**Comment by VanzGantengz** [comment]
common use import?
very nice👌

**Comment by Paguiar735** [comment]
> SyntaxError: Cannot use import statement outside a module

The minimal working example expects you to use TypeScript instead of JavaScript, hence the "bug".

In either case, I do agree that the repository needs some serious refactor to make it easier to get started for newcomers. I tinkered with it for a few days in mid-2021 and the file at "Example/example.ts" worked, but right now I can't get anything to work.

However, I currently I don't have nearly half of what it takes to do that on my own: neither hands-on experience with WebSockets, nor familiarity with the current codebase.

Let me know if any of you is willing to help on that.

**Comment by Paguiar735** [comment]
> SyntaxError: Cannot use import statement outside a module

The minimal working example expects you to use TypeScript instead of JavaScript, hence the "bug".

In either case, I do agree that the repository needs some serious refactor to make it easier to get started for newcomers. I tinkered with it for a few days in mid-2021 and the file at "Example/example.ts" worked, but right now I can't get anything to work.

However, I currently I don't have nearly half of what it takes to do that on my own: neither hands-on experience with WebSockets, nor familiarity with the current codebase.

Let me know if any of you is willing to help with that.

**Comment by frmdeveloper** [comment]
sorry, that has nothing to do with us. it's not baileys fault

**Comment by Paguiar735** [comment]
@M0in4 I'm not sure if you still need it, but I just finished the minimal reproducible example I told you about last month. You can check it [here](https://github.com/Paguiar735/baileys-quickstart).

As for Bailey's current [MRE](https://github.com/adiwajshing/Baileys#Connecting) mentioned in its README and in the documentation, they're still outdated and inoperable.

However, the file in the [Example](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts) folder works so long as you clone the repository instead of adding Baileys as a dependency, which defeats the purpose pushing it to NPMJS.

I'll make a pull request to update them both in Bailey's official repository later.

> > SyntaxError: Cannot use import statement outside a module
> 
> The minimal working example expects you to use TypeScript instead of JavaScript, hence the "bug".
> 
> In either case, I do agree that the repository needs some serious refactor to make it easier to get started for newcomers. I tinkered with it for a few days in mid-2021 and the file at "Example/example.ts" worked, but right now I can't get anything to work.
> 
> However, I currently I don't have nearly half of what it takes to do that on my own: neither hands-on experience with WebSockets, nor familiarity with the current codebase.
> 
> Let me know if any of you is willing to help with that.
