### ISSUE TITLE
[BUG] WhatsApp Number banned

### ISSUE THREAD

**Issue by ravindu01manoj** [adiwajshing/Baileys#2572]
# WhatsApp Number banned

Some numbers are banned while using the code below. 
```ts
 await sock.groupParticipantsUpdate(jid, ['abc@s.whatsapp.net'], 'add')
```
Please tell me if I am doing something wrong or there is any reason

**Comment by officialdittaz** [comment]
> # WhatsApp Number banned
> Some numbers are banned while using the code below.
> 
> ```ts
>  await sock.groupParticipantsUpdate(jid, ['abc@s.whatsapp.net'], 'add')
> ```
> 
> Please tell me if I am doing something wrong or there is any reason

Same with me

**Comment by Paguiar735** [comment]
This could be anything, as WhatsApp's averse to any type of automation that it considers to be "Harm[ful] to WhatsApp or [their] Users" on its platform, unless it's coming from an official WhatsApp Businesses API partner.

You might be making to make requests back-to-back instead of awaiting a few seconds between them.

**Comment by ANUR46** [comment]
> # WhatsApp Number banned
> Some numbers are banned while using the code below.
> 
> ```ts
>  await sock.groupParticipantsUpdate(jid, ['abc@s.whatsapp.net'], 'add')
> ```
> 
> Please tell me if I am doing something wrong or there is any reason

Whatsapp is banning numbers of every new users who are trying to add anyone on the group and the other person number is private and not allowed to add on the group. And whatsapp is banning the number if you do it manually without using Bot automation too. There are many things by doing which whatsapp banned your number. My 10+ numbers get banned with different different reasons. Like joining a group immediately registering the whatsapp and sending messages to any non-contact users firstly until not get message from the user. If you register as bot try to not use add participant to the group. So you can be safe from banning. And make sure your bot not send a lot of message on group or to any users without their requests because its looks like spam. It can also cause to banned the number.
