### ISSUE TITLE
Handle pending message

### ISSUE THREAD

**Issue by tarikhagustia** [adiwajshing/Baileys#264]
Hi @adiwajshing, thanks for your great project!, anyway i have created some REST API to sending message via API, and i meet some problem when sending a message with bad phone internet signal, the message is received but its take a long time and mak HTTP request timeout, because i need to get Whatsapp message ID to save into my database.

any solution for this? thanks

**Comment by itacirgabral** [comment]
Me too...
...and forever. Connection reliability is the challenger because the mobile is always in between.

Maybe less random if baileys and mobile emulation would be side by side on the cloud.

I'm doing message queue. My api receives the request and returns immediately, put it on the queue only.

My free hero:
https://elements.heroku.com/addons/heroku-redis

**Comment by tarikhagustia** [comment]
set `waitForAck` to `false` solve my problem

**Comment by kurnianetwork** [comment]
> `waitForAck`

can u help me where is this code stored?
