### ISSUE TITLE
[BUG] messages don't appear in old groups

### ISSUE THREAD

**Issue by Switzg** [adiwajshing/Baileys#2640]
**Describe the bug**
In an old group, it stopped working, giving a "No Signal" error, I will leave a print below to be clearer (the bot does not recognize any messages anymore and when it is a command, it gives "No Signal").

![Screenshot_2023-03-20-10-11-10-194_com iiordanov freeaRDP](https://user-images.githubusercontent.com/17239183/226348732-34f2d77f-2108-41eb-9ca4-9429267c8c9b.jpg)

**Comment by Switzg** [comment]
It started working again, as if nothing had happened...

**Comment by Switzg** [comment]
> Are you using edge version?

how do i know?

**Comment by Switzg** [comment]
now this...

![Screenshot_2023-03-20-10-19-32-471_com iiordanov freeaRDP](https://user-images.githubusercontent.com/17239183/226352039-e90d1356-29a8-456f-a10b-63925a6b0afd.jpg)

**Comment by Fonnte** [comment]
> now this...
> 
> ![Screenshot_2023-03-20-10-19-32-471_com iiordanov freeaRDP](https://user-images.githubusercontent.com/17239183/226352039-e90d1356-29a8-456f-a10b-63925a6b0afd.jpg)

This happen when you are using latest github version, adi make an update about signal and my app also have many error about public & no sessions like you. 

In my case, when the problem comes out when message is simultanteously sent and received in a short time. 

My suggestion is to try using npm version or using latest version of github before signal update.
