### ISSUE TITLE
Do you have expenses with this repository?

### ISSUE THREAD

**Issue by JuniorRibas** [adiwajshing/Baileys#27]
Good Morning

bro, a question.

Did you raise a server to secure connections to this webSocket?
Is there a limit?

I noticed in my tests that when a cell phone makes a lot of connections it kind of goes through a period without being able to search for contacts

Is this your rule? or is it from the Whatsapp team

I wonder if you have expenses to keep it alive

**Comment by adiwajshing** [comment]
No, its not me. It might be because the phone can't handle so many requests or it's a limit placed by WhatsApp to prevent spamming -- just speculating here. 

Also, Baileys connects directly to WhatsApp Web, I have no server running mediating the connection and hence, no expense associated with the library (besides the time spent on source code maintenance, of course).
