### ISSUE TITLE
[BUG] "Closing stale open session for new outgoing prekey bundle". This bug is very disturbing and causing spam, my bot can't read chats and not working properly.

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#2700]
![image](https://user-images.githubusercontent.com/71264201/230093203-accfa6cc-e0a1-4028-8022-9cd56d5e7fe0.png)

This bug is very disturbing and causing spam, my bot can't read chats and not working properly.

im Using Ubuntu Desktop 22.04 + KDE Desktop Env

**Comment by AlvaroBrasilia** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/2683945/230099613-9a25af59-eaa5-4c9b-9a9b-6b59f3e3bdba.png)

**Comment by souravkl11** [comment]
comes from libsignal

**Comment by AlvaroBrasilia** [comment]
> comes from libsignal

Ok!
What do you mean?
Do you can suggest any solution?

**Comment by kamuridesu** [comment]
How are you implementing the states and storage information?

**Comment by AxeemHaider** [comment]
What this error actually mean?

**Comment by AxeemHaider** [comment]
@Barqah-Xiex did you find any solution ?

**Comment by kamuridesu** [comment]
> What this error actually mean?

It means that the server is closing your connection and sending new keys. 

If you don't handle the new prekey bundle and get rid of the old keys, you'll be using the keys from the old session and this message will be prompted to you every time. 

That's why I asked to see how they're implementing their storage/states.
