### ISSUE TITLE
Is it possible to run the bot 24/7?

### ISSUE THREAD

**Issue by maxymoo22** [adiwajshing/Baileys#45]
Sorry for opening another issue, but you don't seem to have a discord or a place where I can ask quick questions. Anyway, so you scan the QR code with your phone, and then it authorizes baileys. Even if you restart the phone, whatsapp keeps the connection so as long as the phone is turned on, baileys can work. This is pretty good. However, the key thing there is _as long as the phone is turned on._ If you turn off the phone, baileys can no longer connect. Is there any workaround for this? I was thinking you could host  an android virtual machine or something but that does seem like overkill (also how would you scan the QR code initially). If you do know of any simpler methods that work then I'd appreciate it if you could let me know. Thanks.

**Comment by adiwajshing** [comment]
A discord channel is a great idea. You can join this discord [server](https://discord.com/invite/GFJqDdq). It's a general server for WhatsApp APIs. I've asked for a specific channel for Baileys, but feel free to post questions on the server.

To answer your question -- unfortunately, to run it 24/7 you need to either have your phone connected or setup a virtual machine. It's a limitation caused by the way WhatsApp Web works. You can scan the QR code with an emulator, [here](https://stackoverflow.com/a/35526103) is a tutorial on how to do so.

Approaches that directly connect to WhatsApp (like yowsup) typically get banned, so this kind of a roundabout approach is really one's only option.

**Comment by keef3ar** [comment]
i have many connected accounts 24/7, checking connection every 10-10 seconds, handling connection troubles and just trying to connect again, if it can't connect again send notification to check the connected phone.
With phone on charge and whatsapp running on screen uptime is almost 100%
