### ISSUE TITLE
Marker was Not Found! [Get Media with Axios, Cheerio etc..]

### ISSUE THREAD

**Issue by phaticusthiccy** [adiwajshing/Baileys#488]
As we know, Baileys has updated new version to 3.5.0
The update is very good overall, but there are some errors like this issue. Called "**marker was not found**".
This error occurs from any link and when writing a non-local file. I searched and found that the problem was caused by the thumbnail. I'll show you an alternative route for pass this error.
Firstly it's working perfectly but it will not be the same as before. I mean auto thumbnails in media messages.
Step by step:

##

### `Step 1 - Upload a Thumbnail Photo`
Firstly we must upload a photo inside our local files.
I am creating new folder name **media**

![IMG_20210513_202054](https://user-images.githubusercontent.com/74794033/118161861-c1ea9580-b428-11eb-9490-d0ce89864c9a.jpg)
(`mkdir media`)

Then we must upload any thumb inside this folder.

![IMG_20210513_202747](https://user-images.githubusercontent.com/74794033/118162693-b64b9e80-b429-11eb-80b6-d922b226c6d4.jpg)
(`cd media/`) - (`cp {thumb way} {media folder way}`)

### `Step 2 - Adding Function Inside Code`

Now, you must add **↓ this ↓** function inside your code.
```js
const fs = require('fs')
function base64_encode(file) {
    var bitmap = fs.readFileSync(file);
    return new Buffer(bitmap).toString('base64');
}
var base64str = base64_encode("{new thum way}");
```
Here is an example:

![PSX_20210513_203918](https://user-images.githubusercontent.com/74794033/118164049-548c3400-b42b-11eb-9191-2cf5e62d8f77.jpg)

##

### `Step 3 - Add Thumbnail inside Media Messages`

Now after this time, you must use your own structure. We are going to use thumbnail from [here](https://github.com/adiwajshing/Baileys#notes)
When sending media messages, you must use the following code: 
```js
{ **thumbnail: base64str**, mimetype: Mimetype.jpeg, etc.. }
```
Here is an example:

![IMG_20210513_204659](https://user-images.githubusercontent.com/74794033/118164974-64f0de80-b42c-11eb-952a-fd4c1616e8ee.jpg)

##

This is the simple solution to the "marker was not found" error. You can write your comments and suggestions under this issue :)

Special Thanks @adiwajshing for codded Bailyes :)

**Comment by eduardohf14** [comment]
@phaticusthiccy 
(node:119317) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by phaticusthiccy** [comment]
> @phaticusthiccy
> (node:119317) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Buffer.from may solve your problem

**Comment by eduardohf14** [comment]
@phaticusthiccy I'm getting the message:

"This message can't be viewed in WhatsApp Desktop. View it on your phone instead

**Comment by saviosg** [comment]
I spent some time debugging this issue and found a possible solution or a way to find it.

When Baileys needs to generate a thumbnail, it saves the original file to a temporary folder, and it uses a writable stream to write data into the temporary file. [You can check the code here.](https://github.com/adiwajshing/Baileys/blob/master/src/WAConnection/Utils.ts#L362)
In the Node docs it says:
>While a stream is not draining, calls to write() will buffer chunk, and return false. Once all currently buffered chunks are drained (accepted for delivery by the operating system), the 'drain' event will be emitted. It is recommended that once write() returns false, no more chunks be written until the 'drain' event is emitted. While calling write() on a stream that is not draining is allowed, Node.js will buffer all written chunks until maximum memory usage occurs, at which point it will abort unconditionally.

I checked the return value of the function and it does return false. So I did as suggested in the docs:
<details>

![unknown](https://user-images.githubusercontent.com/25729991/118223622-1822fd00-b458-11eb-81a7-f5246958ea21.png)

</details>

Now my code works flawlessly, and it's not slow at all. I have tried stress testing it a bit and it hasn't failed.
I think the problem is some kind of race condition. Baileys doesn't wait for the drain event, so Node keeps the data buffered. When Baileys tries to read the file it fails or the file is incomplete, so the program crashes.
Here's what I found after debugging with strace:
<details>

With my code:
![2021-05-14_01-36](https://user-images.githubusercontent.com/25729991/118222148-700c3480-b455-11eb-8632-e34a0cf24bb1.png)
The file is opened after it was written (look at the file descriptors)

Without my code (file not found):
![2021-05-14_01-35](https://user-images.githubusercontent.com/25729991/118222150-713d6180-b455-11eb-9866-a9f018da4c37.png)
Note that here Node tries to open the file too quickly, before it was even created!

</details>

Maybe the issue is something else, but this might help find out what it is.

**Comment by eduardohf14** [comment]
I solved the problem using the file url instead the stream.

**Comment by ferhacks** [comment]
Up

**Comment by barkerpedro** [comment]
> I spent some time debugging this issue and found a possible solution or a way to find it.
> 
> When Baileys needs to generate a thumbnail, it saves the original file to a temporary folder, and it uses a writable stream to write data into the temporary file. [You can check the code here.](https://github.com/adiwajshing/Baileys/blob/master/src/WAConnection/Utils.ts#L362)
> In the Node docs it says:
> 
> > While a stream is not draining, calls to write() will buffer chunk, and return false. Once all currently buffered chunks are drained (accepted for delivery by the operating system), the 'drain' event will be emitted. It is recommended that once write() returns false, no more chunks be written until the 'drain' event is emitted. While calling write() on a stream that is not draining is allowed, Node.js will buffer all written chunks until maximum memory usage occurs, at which point it will abort unconditionally.
> 
> I checked the return value of the function and it does return false. So I did as suggested in the docs:
> 
> Now my code works flawlessly, and it's not slow at all. I have tried stress testing it a bit and it hasn't failed.
> I think the problem is some kind of race condition. Baileys doesn't wait for the drain event, so Node keeps the data buffered. When Baileys tries to read the file it fails or the file is incomplete, so the program crashes.
> Here's what I found after debugging with strace:
> 
> Maybe the issue is something else, but this might help find out what it is.

It solved the problem with "jpeg" files, but it was giving errors in "pdf" files, so I did it like this:

```node
    const emitter = require("events");
    for await (const data of stream) {
        fileLength += data.length;
        sha256Plain = sha256Plain.update(data);
        writeStream && writeStream.write(data);
        if (writeStream != undefined) {
            if (!writeStream.write(data)) await emitter.once(writeStream, "drain");
        }
        onChunk(aes.update(data));
    }
```
