### ISSUE TITLE
Messages No load [BUG]

### ISSUE THREAD

**Issue by Santy-Gz** [adiwajshing/Baileys#536]
The messages are not loaded in the console and the script does not read them, only the action "promote", "demote", "add" and "remove" is shown in the console, but the other messages do not appear in the console nor are the commands executed . Any solution?

![image](https://user-images.githubusercontent.com/69918140/122229036-ef9f8000-cea7-11eb-8fdb-6faccffad9fe.png)

**Comment by PurpShell** [comment]
talk this on the discord. [Link](https://discord.gg/7FYURJyqng)

Best regards, 

[PurpShell](https://github.com/PurpShell)

**Comment by PurpShell** [comment]
this is **not** a bug report.

**Comment by PurpShell** [comment]
sample code? version information? Other information too??

**Comment by PurpShell** [comment]
have you forgotten to use this template? 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**
Add any other context about the problem here.

**Comment by Santy-Gz** [comment]
Describe the bug:
The messages are not loaded in the console and the script does not read them, only the action "promote", "demote", "add" and "remove" is shown in the console, but the other messages do not appear in the console nor are the commands executed . Any solution? 

To Reproduce
Steps to reproduce the behavior:

Created a new connection
Login whith qr code 
Try run the commands

Environment (please complete the following information):

Is this on a server?
In rdp 
What do your connectOptions look like?
All rigth only messages in console not work's 
Do you have multiple clients on the same IP?
Nope 
Are you using a proxy?
Nope

Additional context

this problem occurred 3 days ago days before the script was working correctly
