### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by sudhartioeric** [adiwajshing/Baileys#538]
hello sir, i can't scan barcode :( barcode qr is showing but my whatsapp cannot detect connect

**Comment by horlahlekhon** [comment]
The issue is caused by whatsapp recent changes,  they have changed initial message authentication message structure, it doesn't include client connection timestamp anymore. 
form this
["admin","init",[0,4,1296],["Chromium at 2021-06-17T03:04:41.178","Chromium"],"5zS+1ix5TFwX+81utHPofg==",true]  `

to 

`["admin","init",[2,2123,7],["Mac OS","Chrome","10.15.7"],"LMmsecxAhrW62l+P+/cbhg==",true]`

that simple change got it working on my side. hope it helps.

**Comment by sudhartioeric** [comment]
oky thnks bro
