### ISSUE TITLE
Get contact's current presence

### ISSUE THREAD

**Issue by alirezadigi** [adiwajshing/Baileys#662]
Hi!
How can i get contact's current presence status?
For example in a while loop?
Not just the change of presence.

**Comment by PurpShell** [comment]
I answered your question on the discord, and yet you have the audacity to open an issue here, when the body of this issue is clearly not a bug report nor a feature request. I hate this behavior. Not that but also WHY WHILE LOOPS :D, learn javascript [here](https://codecademy.com/learn/introduction-to-javascript) because at this point you are just a broken radio

**Comment by alirezadigi** [comment]
with help of a friend who knows js we wrote a program. But it seems to be undefined in the baileys code.
We cant get online status of a person. We can just get (Typing , Sending voice , etc) status with baileys.
But i want to get online status even if user isnt typing.
