### ISSUE TITLE
add call feature

### ISSUE THREAD

**Issue by affisjunianto** [adiwajshing/Baileys#675]
for adiwajshing

please add the call and video call feature so we can be more updated in the future

**Comment by FaizBastomi** [comment]
> please add the call and video call feature

if on WhatsApp Web there is a calling feature, maybe Baileys can make calls because basically Baileys is connected to WhatsApp Web. Ask WhatsApp when the calling feature will be available in the Web version.

If your WhatsApp Web has a calling feature, maybe you can do a little experiment and pass on the code you use to allow making calls through Baileys.

If you have any other questions, please join our discord server😄. [click me](https://discord.gg/7FYURJyqng)

**Comment by affisjunianto** [comment]
thanks for replying my message

Pada tanggal Min, 29 Agu 2021 18.36, ファイズ ***@***.***>
menulis:

**Comment by FaizBastomi** [comment]
if there are no other questions, I hope you can close this issue.

**Comment by affisjunianto** [comment]
nice
