### ISSUE TITLE
request featurr

### ISSUE THREAD

**Issue by affisjunianto** [adiwajshing/Baileys#681]
hi bro

can you add a snapshot feature for WhatsApp web screen screenshots like wa automate

**Comment by FaizBastomi** [comment]
it doesn't seem possible because Baileys is directly connected via a websocket and doesn't interact with the WhatsApp Web GUI that is usually accessed with a browser.
***
If you have questions or feature requests, please discuss them first on the discord server.  Join the discord server now! [here](https://discord.gg/7FYURJyqng)

**Comment by affisjunianto** [comment]
hei bung

u can update feature for whatsapp web beta . multidevice :)

Pada tanggal Min, 5 Sep 2021 00.54, ファイズ ***@***.***> menulis:

**Comment by FaizBastomi** [comment]
We know WhatsApp multi-device has started showing up in the linked devices option as a beta feature.  We're also working hard to get Baileys stable as soon as possible with the "multi-device" feature.  For more information, please read the comments on the following issue. #605

**Comment by frmdeveloper** [comment]
Awokawokawok
request ribet
