### ISSUE TITLE
Unsent List Type Messages

### ISSUE THREAD

**Issue by jmas005** [adiwajshing/Baileys#686]
List type messages do not reach the recipient, any suggestions for solving this problem?

![media_in_43A5324E96B66F867315A0DFC7414657](https://user-images.githubusercontent.com/73140494/132313434-e65df323-e110-4cdf-a6e3-238605c7ff54.jpeg)

**Comment by FaizBastomi** [comment]
Are you on WhatsApp Business?
WhatsApp Business can't send that message because it's limited by the WhatsApp app itself (to my knowledge), I recommend using the regular WhatsApp instead of the business one.

If you have other questions, please reply to this comment or continue on the discord server because this issue is not related to Baileys. [discord server](https://discord.com/invite/7FYURJyqng)
