### ISSUE TITLE
[BUG] - [.sendReadReceipt]  - The function does not work.

### ISSUE THREAD

**Issue by mateuscdor** [adiwajshing/Baileys#972]
[.sendReadReceipt] 
(https://github.com/adiwajshing/baileys/tree/multi-device#reading-messages)

The function does not work.
I've tried in other ways
more unsuccessful.

Version used: Baileys-md
await sock.sendReadReceipt(id, participant, [messageID])

@adiwajshing

**Comment by HUGEIT** [comment]
no one can help if you do not post code.

**Comment by mateuscdor** [comment]
await sock.sendReadReceipt(id, participant, [messageID])

**Comment by phaticusthiccy** [comment]
S/he is talking about the whole code 🤦‍♂️

**Comment by mateuscdor** [comment]
> S/he is talking about the whole code 🤦‍♂️ Its the bas, you sent.

does your code work?
Baileys-md in multi-device version?

could post the script you use?

**Comment by phaticusthiccy** [comment]
Dude `SEND the Code` if you wanna us to help you.

**Comment by mateuscdor** [comment]
The group confirmed, it is not working.
The lib is buggy

@adiwajshing

**Comment by adiwajshing** [comment]
@mateuscdor two people have already asked you to post your full code, since you're reluctant to do that -- I'm closing the issue. If you find the lib buggy & are unwilling to provide enough information to debug, there are other libs available, you are free to use them. I hope I've made myself clear.
